### ISSUE TITLE
json-to-biopax:  'active'/'inactive' state of controlled participants from Factoid "Protein Modification"  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#1]
@metincansiper 

Noticed declaring a phosphorylation relation within Factoid generates BioPAX whereby the controlled/conversion left and right participants have ModificationFeatures 'inactive' and 'active', respectively. The features should not be applied.

Example: [CDK2 phosphorylates RB1](http://unstable.factoid.baderlab.org/document/6e90d23a-1bc3-4506-b6ac-109d43226795/4185d265-78d4-4c50-9036-1fecba906436): Perhaps the intention is to apply to the control:controlType?
![screenshot_factoid_cdk2pnrb1](https://user-images.githubusercontent.com/4706307/45897616-a4fb8280-bda5-11e8-9c5b-7498f2bf2c7e.png)

ChiBE:
![screenshot_chibe_cdk2pnrb1](https://user-images.githubusercontent.com/4706307/45897638-b17fdb00-bda5-11e8-9041-30a453dc1cf2.png)

**Comment by IgorRodchenkov** [comment]
json-to-biopax is @metincansiper Metin's code; so go ahead.

**Comment by metincansiper** [comment]
Thanks @jvwong. @ozgunbabur do you have any opinion about this?

**Comment by ozgunbabur** [comment]
When it is phosphorylation, the modified protein should have a featureless state and a phosphorylated state. The inactive and active modification features are applicable only when the control is about activation/inhibition.

**Comment by jvwong** [comment]
Ask the experts: Is the notion of 'activation/inhibition' discouraged in BioPAX? It doesn't appear to 'fit'.

**Comment by IgorRodchenkov** [comment]
It's not, but it applies to processes. Control.controlType can be activation or inhibition; Catalysis.controlType should be always activation. That's pretty it. One can only fantasize and dream (infer) about a physical entity being active, activated or suppressed, inactive, etc.. (sometimes you can tell by looking in the features and comments...)

**Comment by ozgunbabur** [comment]
Yes, BioPAX is not designed to generate models at this level of abstraction. Active/inactive is a binary annotation, however biology is more complex. There can be many activities of proteins and complexes. The proper model will describe the modification that the protein gets, and will model each downstream activity as a separate conversion of other molecules, linking the protein and those downstream conversions with applicable Control objects.

Saying A activates B means omitting both the modification of B and the specific downstream activity of B. NCI PID uses those very often. One way-around to include those models in Pathway Commons is to treat active/inactive annotations as if they are protein modifications in BioPAX.

**Comment by jvwong** [comment]
Yes - this is what I've seen from [PID](http://apps.pathwaycommons.org/pathways?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FCatalysis_c68259f67910648ea467d8e8f94f896c) and why I was unsure: 

![http 3a 2f 2fpathwaycommons org 2fpc2 2fcatalysis_c68259f67910648ea467d8e8f94f896c](https://user-images.githubusercontent.com/4706307/46682848-afe34f00-cbbc-11e8-9b50-90c8f4716eaa.png)

**Comment by jvwong** [comment]
The model discussion and updates will likely make this go away. Will reopen if necessary.
