### ISSUE TITLE
Handling interactions with complexes and their component(s)  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#17]
Background: Factoid, allows edges to connect complex components. For BioPAX, interactions occur with the complex as participant.

Issue: In Factoid, when a complex component is involved in an interaction, the corresponding BioPAX disregards/eliminates the complex entirely. I don't think we intended to throw away this information.

- Example
  - Factoid: https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880

<img src="https://biofactoid.org/api/document/e1e4b079-258d-4258-b5a2-3a665046d880.png" height="200px" />

  - BioPAX: https://biofactoid.org/api/document/biopax/e1e4b079-258d-4258-b5a2-3a665046d880
  - SBGN: https://apps.pathwaycommons.org/factoids/e1e4b079-258d-4258-b5a2-3a665046d880  

<img src="https://user-images.githubusercontent.com/4706307/98704843-20846900-234b-11eb-9a1b-21672f3deb69.png"  height="200px" />

Aside: Get a list of available Factoid document links to the SBGN view (https://apps.pathwaycommons.org/factoids/)

**Comment by metincansiper** [comment]
@jvwong see https://github.com/PathwayCommons/factoid/pull/927
