### ISSUE TITLE
Design and use a new input JSON format (to be generated by Factoid)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/factoid-converters#2]
The Factoid model is about to change, and there are new and re-defined interaction types.

Metin wrote:

> I went over the document and the json format. There are a few things that are not satisfied by the existing json format. 
> In Transcription/translation the source (A) can be either a chemical or protein now. However, the json structure assumes that A will be a protein and assigns "transcriptionFactor" field to it. I think changing this field as "source" and adding a new field like "sourceType" (would be either protein or small molecule) would be needed. 
> For Other-A (4-A) there is no matching type in json schema. We need to add a type to cover it. How about naming it as "General Interaction"?
> There would be more need to improve the type names etc. but I think these two may be needed to go forward even for the beginning.

I agree that we shall change most interaction type names (e.g., "type": "Protein Controls State", etc.) in the [intermediate JSON format](https://github.com/PathwayCommons/factoid-converters/blob/master/src/test/resources/test.json) to match and expand what we've discussed. 
So, I suggest the following.

1. Update current intermediate input JSON format to support new Factoid model features;
see [the doc](https://docs.google.com/document/d/1mN6_v9JfGJRW0lBLOncLZtZh_fEuakGQkAfG1Mu08QY/view#heading=h.7j1j758vqyn6)

2. Optimize input JSON format, make simpler and more consistent, i.e, instead

```
"controllerProtein": {
  "name": "pcs_controllerProtein",
  "xref": {
    "id": "xref1.1",
    "namespace": "uniprot"
  }
},
```
should be:
```
"controller": {
  "type":"Protein",
  "name": "A",
  "xref": {
    "id": "xref1.1",
    "db": "uniprot"
  }
},
```
i.e., instead of using many different keys that encode type in them ("controllerProtein", "chemical", "transcriptionFactor", "chemicalList", etc.), better use consistently just a few simple keys like "source", "target", "controller" (-"source" would work here too), etc., and additional "type" key inside the entity object. Also, as I see it in current json input format, the interaction type often (I bet always) defines the both types of participants! Also, "namespace" there in xref is probably not about a namespace but rather about xref.db property (which should not normally have MIRIAM/Identifiers.org namespace as its value; only standard names are there valid; in case of "uniprot", namespace and name are the same thing, but it's not true for other data collections, such as "Uniprot Isoform", "PubChem Compound").

@metincansiper 
Lets create a new example test2.json file in src/test/resources and then do #3 to work with it.

**Comment by IgorRodchenkov** [comment]
Those entity type values come naturally, “for free”, from Factoid model. Don’t worry about user put wrong types there, it’s impossible by design. Should Factoid interactions model change in the future, we will have to modify the factoid-converters accordingly, anyway. I think, currently, the model and new biopax-ish json format give us sufficient flexibility for implementing the converter to biopax, especially for case 4A-E “Other” association types. It’s better than hardcoding types in keys, like “controllerProtein” and depending on it.

IR

**Comment by IgorRodchenkov** [comment]
@metincansiper
The test2.json is not just an example I wrote; it’s actual output from doc.toBiopaxTemplates from the updated factoid (merged into unstable branch today); run, play with it, see the intermediate json output in the chrome dev. console... Of course we can modify the model further if needed, but I think it does what we wanted according the factoid interaction types doc (biopax sections 1 - 4E).

**Comment by metincansiper** [comment]
Yes sure, for us the only client is factoid. I just wondered how does it sound to make it free from biopax view of point. Looks like it is okay, so we can always respect the user input for the type instead of inferring the types.

**Comment by IgorRodchenkov** [comment]
Factoid UI is supposed to provide such workflow that almost makes sure the interaction models make sense, and in worst case it probably generates the “other” type, which we will classify in the converter. I prefer having less biopax specific code (if-else constructs, etc) in the factoid modules and rather do it in java in the converter.

**Comment by IgorRodchenkov** [comment]
Done. If there is any unforeseen problem with converting this format to biopax using java and paxtools, let's open another issue (but i think. there's no). 

PS:
Again, we focus on this converter, and can do almost everything here in java, while minimizing biopax-specific never-good-enough javascript code in Factoid app. Our main requirement here is for Factoid to produce reasonable and flexible JSON doc without overthinking it by doing part of converter's job on Factoid's side instead here (e.g. using many keys, types that encode very specific biopax classes or properties was not a good idea, and did't in fact make this factoid-converters development much easier) .

**Comment by metincansiper** [comment]
@IgorRodchenkov test2.json looks good to me in general. But I think there is one missing case. For ``Protein Controls State`` example in the file there is no modification type parameter. I think we can add it as well. How about naming it as ``modificationType``. I think for factoid modal always there is a modification type but we can still support the case where it is not available as in the example. 

Also maybe changing the type name as ``Controls State`` would be considered (since we are taking controller type as input it may be self contradicting to name it as  ``Protein Controls State``) but it is not a big deal at all.

**Comment by metincansiper** [comment]
Oh I just read the last comment after commenting here. We can create a new issue if needed but what I am asking for is not a big change.

**Comment by IgorRodchenkov** [comment]
So, metin, there is line of code
<https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/interaction-type/modification.js#L51>
which
would include *'effect'* field into the "biopax" template in case of any
sub-class of Modification.
In the test2.json example
<https://github.com/PathwayCommons/factoid-converters/blob/master/src/test/resources/test2.json#L272>
it just happened to be no such case, otherwise there would be e.g. "Protein
controls state" with 'effect':"phosphorylated"...
See e.g. this
<https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/interaction-type/phosphorylation.js#L13>
.

**Comment by metincansiper** [comment]
Looks like that data is still passed to json as ``modification`` instead of ``effect`` (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/interaction-type/modification.js#L52). We will need to update that line too.

**Comment by IgorRodchenkov** [comment]
example?

IR

**Comment by IgorRodchenkov** [comment]
Ah, yes, the field that holds effect is named as modification, sorry

IR

**Comment by IgorRodchenkov** [comment]
Let’s keep it as ‘modification’, it doesn’t matter much (‘effect’ was just factoid internal variable name, which is no better than ‘modification’ or ‘feature’ or alike we could use)

IR
