### ISSUE TITLE
BioPAX: Reference to biofactoid pathway id

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#20]
It would be valuable to have a reference from the BioPAX to the Biofactoid document `id`. I don't think this currently exists?

e.g.  BioPAX for ["The Fatty acid cycling model" (Reactome)](https://www.pathwaycommons.org/pc2/get?format=biopax&uri=http://identifiers.org/reactome/R-HSA-167826) references Reactome's db/id (i.e. reactome/R-HSA-167826).

**Comment by metincansiper** [comment]
@jvwong #21 and https://github.com/PathwayCommons/factoid/pull/928 solves this together.

**Comment by jvwong** [comment]
Is the implementation using the Biofactoid `id` as the `<bp:Pathway` resource ? Or is it in an xref?

I'm seeing this (e.g. biofactoid doc id = 00e31cb6-e8f4-4abb-9c9d-e03dc82fda5a)
```xml
 <bp:Pathway rdf:about="00e31cb6-e8f4-4abb-9c9d-e03dc82fda5a">
    <bp:pathwayComponent rdf:resource="b510f1aa-f85d-465f-9454-d1661643b0a2" />
    ...
    <bp:xref rdf:resource="aea79cd3-6a12-4944-abb1-72fdc23aeb06" />
    <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Butyrate produced by gut commensal bacteria activates TGF-beta1 expression through the transcription factor SP1 in human intestinal epithelial cells.</bp:displayName>
  </bp:Pathway>
...
```

**Comment by metincansiper** [comment]
>Is the implementation using the Biofactoid id as the <bp:Pathway resource ? Or is it in an xref?
I'm seeing this (e.g. biofactoid doc id = 00e31cb6-e8f4-4abb-9c9d-e03dc82fda5a)

I set the id of Biofactoid document as the id of pathway component since I realized that ``rdf:about`` value is determined by the pathway id. Is not that what you wanted?

**Comment by jvwong** [comment]
I think that leaves some ambiguity as to what the id value is.

**Comment by metincansiper** [comment]
@jvwong should I just revert these changes then?

**Comment by jvwong** [comment]
I'm noticing its implemented elsewhere as a `UnificationXref`

**Comment by metincansiper** [comment]
@jvwong would you provide the example that you have noticed it?

**Comment by metincansiper** [comment]
In this case we only have the document id. May it be like a unification xref where the id is the biofactoid document id and the db is set to ``biofactoid``?

**Comment by jvwong** [comment]
Yes I was looking at something like this: https://www.pathwaycommons.org/pc2/get?format=biopax&uri=http://identifiers.org/reactome/R-HSA-167826 

```xml
...
 <bp:Pathway rdf:about="http://identifiers.org/reactome/R-HSA-167826">
    <bp:xref rdf:resource="#UnificationXref_reactome_R-HSA-167826" />
     ...
    <bp:dataSource rdf:resource="#Provenance_2fd94e28e36931796fb9119fad6d4003" />
  </bp:Pathway>
...
 <bp:UnificationXref rdf:ID="UnificationXref_reactome_R-HSA-167826">
    <bp:idVersion rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">2</bp:idVersion>
    <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Reactome stable identifier. Use this URL to connect to the web page of this instance in Reactome: http://www.reactome.org/cgi-bin/eventbrowser_st_id?ST_ID=R-HSA-167826.2</bp:comment>
    <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">R-HSA-167826</bp:id>
    <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">reactome</bp:db>
  </bp:UnificationXref>
...
```

**Comment by jvwong** [comment]
That reminds me I wonder if we should look into this: https://registry.identifiers.org/prefixregistrationrequest#! under the purview of making data connected, FAIR etc.

**Comment by metincansiper** [comment]
>That reminds me I wonder if we should look into this: https://registry.identifiers.org/prefixregistrationrequest#! under the purview of making data connected, FAIR etc.

One of the groups in the form is about the "Namespace Details". I created a proposal to fill that form:

```
Namespace Name: BioFactoid
Description: A web-based system that empowers authors to capture and share machine-readable summaries of molecular-level interactions described in their publications.
Requested Prefix: biofactoid
Sample Id: 4e7885d5-f01c-4fbe-9937-f4d1b5ff53ab
Regex pattern: [0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12} 
(as in this url that someone created: https://www.regextester.com/99148)
Supporting references (Optional):
Additional information (Optional):
```

However, there are other groups like "Institution details", "Provider details", "Requester details". I thought that it would be more convenient if someone other then myself would fill that other groups and so complete the request. Do you agree?

**Comment by jvwong** [comment]
OK thanks for starting this - I will follow up!

**Comment by metincansiper** [comment]
>Yes I was looking at something like this: https://www.pathwaycommons.org/pc2/get?format=biopax&uri=http://identifiers.org/reactome/R-HSA-167826

Okay I updated the code to add a unification xref with the model id. I set the db of xref as ``BioFactoid`` for now we can update it if needed after namespace for biofactoid is created.
