### ISSUE TITLE
Differences in a participant's state/feature leads to disconnected pathway in biopax/sbgn 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#28]
In examining several SBGN versions of pathways derived from Biofactoid, have noticed when a state-change is involved, it leads to a 'disjoint' or break in the set of interactions. Clearly, this is because assigning state (even explicitly assigning the absence of a feature/modification) creates distinct pools of the entity. At best it looks odd to have a single binary network (in biofactoid/SIF) look like multiple disjoint interaction sets (e.g. in PC/SBGN).

Illustrate this with an example for [Waters et al. Cell Rep (2021)](https://biofactoid.org/document/69e71b02-82db-4f12-ac5b-0fd3d68dba48):
<img width="600" alt="Screen Shot 2022-06-27 at 5 47 02 PM" src="https://user-images.githubusercontent.com/4706307/176041367-12af9f16-93f0-4934-aab0-b7062381dec7.png">

The corresponding [BioPAX/SBGN version(viewed in pc apps)](https://appsbeta.pathwaycommons.org/pathways?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc13%2FPathway_81ca40a63b8cd13eac953b56331918ad)

<img width="600" alt="pcapps_Targetingp130Cas" src="https://user-images.githubusercontent.com/4706307/176041484-4a341b41-cdcc-4323-be58-d7b1218f6e12.png">

Note that BCAR1 above is the official symbol for p130Cas (in biofactoid).

---

While this seems technically correct, it appears strange to take each interaction 'out of context' from other interactions. I wonder if there is a better way to handle this type of conversion.

**Comment by gbader** [comment]
A reaction/interaction would be needed to link these entities. One could be
created automatically by biofactoid. We'd need to analyze examples to see
what interaction types are needed.

**Comment by jvwong** [comment]
> A reaction/interaction would be needed to link these entities. 

I can post more examples below.

---

For the above example, it occurs to me that the author intended to say that "Phosphorylated form of p130Cas (BCAR1-p) activates DOCK1" so perhaps there's indeed something lost in the translation.

**Comment by jvwong** [comment]
Example with modifications splitting a pathway in 3 chunks [Zheng et al. Theranostics (2019)](https://biofactoid.org/document/0238ca0a-b349-44df-86e3-2ebca6b949f8):

Biofactoid doc:
<img width="500" alt="biofactoid" src="https://user-images.githubusercontent.com/4706307/176225784-22bc1016-3cbf-4745-8d65-d7fc2e26ef89.png">

BioPAX/SBGN 

<img width="500" alt="SBGN" src="https://user-images.githubusercontent.com/4706307/176225917-988f0325-9365-4a13-be3f-aac83f8f941d.png">

**Comment by gbader** [comment]
Could you link to the biopax?

**Comment by jvwong** [comment]
I linked it above and in #30

**Comment by jvwong** [comment]
I think there's two separate issues in the previous discussion worth distinguishing:

1) Participant is assigned some state and is inferred from the Biofactoid based on the type of interaction. For instance, a modification in Biofactoid translates to a BioPAX control/conversion where the controlled participant gets some state via the converter. This, in fact, is by design, and was discussed in the "Factoid binary interaction types" Google Doc.

e.g. https://github.com/PathwayCommons/factoid-converters/issues/28#issue-1286462115

2) Duplicate. This seems to be a bug.

e.g. #30
