### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#7]
I couldn't get the Dockerized version to run using either gradle or in DockerHub (https://hub.docker.com/repository/docker/pathwaycommons/factoid-converters).

It would be nice to incorporate this as an image in our Factoid docker-compose...

**Comment by jvwong** [comment]
```
> iMac factoid-converters % ./gradlew build docker      

> Task :test

factoid.model.BioPAXModelTest > addControlTest FAILED
    java.lang.AssertionError at BioPAXModelTest.java:142

factoid.model.BioPAXModelTest > addPhysicalEntityTest FAILED
    java.lang.AssertionError at BioPAXModelTest.java:60
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector /3a3c6a62719d967175b76b63925f1fb495f11437/jaxb-impl-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-21 15:00:41.291  INFO 14090 --- [       Thread-9] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

17 tests completed, 2 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
7 actionable tasks: 1 executed, 6 up-to-date
```

**Comment by IgorRodchenkov** [comment]
Is this in the unstable branch or both? Revert or fix the latest changes in the unstable. test before pushing.

**Comment by metincansiper** [comment]
There was a specific problem related to tests in unstable I fixed that but docker build is still not working. After fixing the problems that I mentioned it is not working in the same way for both of master and unstable. Regular build works though. The remaining error is:

```
> Task :docker FAILED
invalid argument "/factoid-converters" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docker'.
> Process 'command 'docker'' finished with non-zero exit value 125

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
10 actionable tasks: 3 executed, 7 up-to-date
```

It probably read nothing or an empty string from ``${project.group}`` here (https://github.com/PathwayCommons/factoid-converters/blob/master/build.gradle#L52). That results in evaluating "/factoid-converters" which is mentioned as the invalid argument. I tried to update that name as a valid argument like "factoidconverters" just to see what will happen. This time the execution stucks at 93%.

I am trying to fix it.

**Comment by IgorRodchenkov** [comment]
I can try to fix the docker build (and upgrade gradle wrapper, docker plugin, etc.) and submit a PR

**Comment by IgorRodchenkov** [comment]
There is a PR: https://github.com/PathwayCommons/factoid-converters/pull/8

**Comment by metincansiper** [comment]
Great, thank you for the PR!

**Comment by metincansiper** [comment]
The docker build is successful in my computer but not in the dockerhub. I guess that is is because ``./gradlew build`` is required to run before the docker build. I will look into removing that requirement to build a docker image.

**Comment by metincansiper** [comment]
Automated docker build is successful with my last commit where I forgot to tag this issue. If any one has no other concern we can close the issue.

**Comment by jvwong** [comment]
Works for me.
